
// ── Share via URL ─────────────────────────
document.getElementById('share-btn').addEventListener('click', () => {
  const params = new URLSearchParams();
  Object.entries(cfg).forEach(([k, v]) => {
    if (v !== DEFAULTS[k]) params.set(k, v);
  });
  const colorsOn = palette.filter(c => c.on).map(c => c.hex);
  const defaultOn = PALETTE_HEX;
  if (JSON.stringify(colorsOn) !== JSON.stringify(defaultOn)) {
    params.set('pal', palette.map(c => c.on ? c.hex : '0').join(','));
  }
  const custStr = customPalette.filter(c => c.hex).map(c => (c.on ? '' : '!') + c.hex).join(',');
  if (custStr) params.set('cust', custStr);
  if (activeShapes.join(',') !== 'rect') params.set('shapes', activeShapes.join(','));
  if (mode !== 'burst') params.set('mode', mode);
  const url = location.origin + location.pathname + '?' + params.toString();
  navigator.clipboard.writeText(url).then(() => {
    const btn = document.getElementById('share-btn');
    btn.textContent = '✅ Copied!';
    setTimeout(() => btn.textContent = '🔗 Share', 2000);
  }).catch(() => {
    prompt('Copy this URL:', url);
  });
});

// ── Clear / Reset ──────────────────────────
document.getElementById('clear-btn').addEventListener('click', () => {
  particles = [];
  if (animId) { cancelAnimationFrame(animId); animId = null; }
  ctx.clearRect(0, 0, testArea.clientWidth, testArea.clientHeight);
  pcEl.textContent = 'particles: 0';
});
document.getElementById('reset-btn').addEventListener('click', () => {
  Object.entries(DEFAULTS).forEach(([k,v]) => {
    const inp = document.getElementById('s_'+k);
    if (inp) { inp.value = v; inp.dispatchEvent(new Event('input')); }
  });
  document.getElementById('bg-color').value = '#1a1a2e';
  testArea.style.background = '#1a1a2e';
  // Reset default palette to original colors
  palette.forEach((c,i) => {
    c.hex = c.orig; c.on = true;
    const el = swDefault.children[i];
    el.style.background = c.hex;
    el.classList.remove('off'); el.classList.add('on');
    el.querySelector('input[type=color]').value = c.hex;
    el.querySelector('.swatch-x').style.display = 'none';
  });
  // Clear custom slots
  customPalette.forEach((c,i) => {
    c.hex = null; c.on = false;
    const slot = swCustom.children[i];
    slot.style.background = '';
    slot.childNodes[0].textContent = '+';
    slot.classList.remove('has','on','off');
    slot.querySelector('input[type=color]').style.pointerEvents = 'auto';
  });
});

// ── Export code ────────────────────────────
function genCode() {
  const colors = getColors(), shapes = activeShapes, c = cfg;
  return `<!-- ══════════════════════════════════════════════════════════
  Confetti Effect — generated by Confetti Lab v3.2
  ────────────────────────────────────────────────────────────
  1. Paste this entire block before </body> in your HTML page.
  2. Call launchConfetti(x, y) or launchConfettiBloom(x, y).

     // Side-view burst on click:
     document.addEventListener('click', e =>
       launchConfetti(e.clientX, e.clientY));

     // Bloom Burst (overhead 360° bloom):
     document.getElementById('myBtn').addEventListener('click', () =>
       launchConfettiBloom(innerWidth / 2, innerHeight / 2));

     // Side-view from center on button:
     document.getElementById('myBtn').addEventListener('click', () =>
       launchConfetti(innerWidth / 2, innerHeight / 2));
═══════════════════════════════════════════════════════════ -->

<canvas id="confetti-canvas" style="position:fixed;inset:0;
  width:100%;height:100%;pointer-events:none;z-index:9999;"></canvas>

<script>
(function () {

  /* ── Your settings (exported from Confetti Lab session) ─ */
  const C = {
    count:   ${Math.round(c.count)},    // particles per burst
    spread:  ${c.spread},   // spawn radius px around origin
    vx:      ${c.vx},       // horizontal velocity range (±half)
    vy:      ${c.vy},       // max upward velocity
    vyMin:   ${c.vyMin},    // min upward velocity
    wind:    ${c.wind},     // drift per frame (neg=left, pos=right)
    gravity: ${c.gravity},  // downward acceleration per frame
    drag:    ${c.drag},     // velocity multiplier (1=off, 0.98=some air)
    spin:    ${c.spin},     // max tumble rad/frame
    fade:    ${c.fade},  // alpha lost per frame (lower = longer life)
    wMax:    ${c.w},        // max particle width px
    hMax:    ${c.h},        // max particle height px
    sizeVar: ${c.sizeVar},  // size randomness: 0=uniform 1=max
    shapes:  ${JSON.stringify(shapes)},
    colors:  ${JSON.stringify(colors)},
  };

  /* ── Canvas ─────────────────────────────────────────────── */
  const cv = document.getElementById('confetti-canvas');
  const cx = cv.getContext('2d');
  function resize() {
    const d = devicePixelRatio || 1;
    cv.width = innerWidth * d; cv.height = innerHeight * d;
    cx.setTransform(d, 0, 0, d, 0, 0);
  }
  resize();
  window.addEventListener('resize', resize);

  /* ── Public API ─────────────────────────────────────────── */
  let P = [], rid = null;
  window.launchConfetti = function (x, y) {
    const vm = C.sizeVar;
    for (let i = 0; i < C.count; i++) P.push({
      x: x + (Math.random()-.5)*C.spread, y,
      vx: (Math.random()-.5)*C.vx,
      vy: -(Math.random()*C.vy+C.vyMin),
      w: C.wMax*(1-vm*.5)+Math.random()*C.wMax*vm,
      h: C.hMax*(1-vm*.5)+Math.random()*C.hMax*vm,
      color: C.colors[Math.floor(Math.random()*C.colors.length)],
      rotation: Math.random()*Math.PI*2,
      rv: (Math.random()-.5)*C.spin,
      alpha: 1,
      shape: C.shapes[Math.floor(Math.random()*C.shapes.length)],
    });
    if (!rid) rid = requestAnimationFrame(tick);
  };

  /* ── Bloom Burst (overhead 360° bloom) ─────────────── */
  const BL = 1 / Math.max(C.fade, 0.001);
  window.launchConfettiBloom = function (x, y) {
    const vm = C.sizeVar;
    for (let i = 0; i < C.count; i++) {
      const a = Math.random()*Math.PI*2;
      const sp = Math.random()*C.vy+C.vyMin;
      const d = 0.6+Math.random()*0.8;
      P.push({
        x, y, _ox:x, _oy:y,
        vx: Math.cos(a)*sp, vy: Math.sin(a)*sp,
        w: C.wMax*(1-vm*.5)+Math.random()*C.wMax*vm,
        h: C.hMax*(1-vm*.5)+Math.random()*C.hMax*vm,
        color: C.colors[Math.floor(Math.random()*C.colors.length)],
        rotation: Math.random()*Math.PI*2,
        rv: (Math.random()-.5)*C.spin,
        alpha:1, _a:0, _l:BL, _d:d,
        _bs:0.15+d*0.1, _ps:0.7+d*0.55, _es:0.25+d*0.15,
        shape: C.shapes[Math.floor(Math.random()*C.shapes.length)],
      });
    }
    if (!rid) rid = requestAnimationFrame(tick);
  };

  /* ── Shape renderer ─────────────────────────────────────── */
  function draw(p) {
    const hw=p.w/2, hh=p.h/2; cx.fillStyle=p.color;
    switch(p.shape){
      case 'rect':cx.fillRect(-hw,-hh,p.w,p.h);break;
      case 'circle':cx.beginPath();cx.ellipse(0,0,hw,hh,0,0,Math.PI*2);cx.fill();break;
      case 'tri':cx.beginPath();cx.moveTo(0,-hh);cx.lineTo(hw,hh);cx.lineTo(-hw,hh);cx.closePath();cx.fill();break;
      case 'star':{const r=Math.max(hw,hh),ri=r*.38;cx.beginPath();
        for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,d=i%2?ri:r;
        i?cx.lineTo(Math.cos(a)*d,Math.sin(a)*d):cx.moveTo(Math.cos(a)*d,Math.sin(a)*d);}
        cx.closePath();cx.fill();break;}
      case 'line':{const l=Math.max(hw,hh)*2;cx.fillRect(-l/2,-1.5,l,3);break;}
      default:cx.fillRect(-hw,-hh,p.w,p.h);
    }
  }

  /* ── Animation loop ─────────────────────────────────────── */
  function tick() {
    cx.clearRect(0,0,innerWidth,innerHeight);
    let alive=false;
    for(const p of P){
      let sc=1;
      if(p._bs!=null){
        p._a++;
        const t=Math.min(p._a/p._l,1);
        p.vx=(p.vx+C.wind*.01)*C.drag; p.vy=p.vy*C.drag;
        if(t>0.55){const dx=p._ox-p.x,dy=p._oy-p.y,di=Math.sqrt(dx*dx+dy*dy)||1;
          const pl=C.gravity*0.3*Math.min((t-0.55)/0.45,1);
          p.vx+=(dx/di)*pl; p.vy+=(dy/di)*pl;}
        if(t<0.3){const e=t/0.3;sc=p._bs+(p._ps-p._bs)*(1-(1-e)*(1-e));}
        else if(t<0.65){sc=p._ps;}
        else{const e=(t-0.65)/0.35;sc=p._ps+(p._es-p._ps)*e*e;}
      }else{
        p.vx=(p.vx+C.wind*.01)*C.drag; p.vy=p.vy*C.drag+C.gravity;
      }
      p.x+=p.vx; p.y+=p.vy; p.rotation+=p.rv; p.alpha-=C.fade;
      if(p.alpha<=0||p.x<-80||p.x>innerWidth+80||p.y<-80||p.y>innerHeight+80) continue;
      alive=true;
      cx.save(); cx.globalAlpha=p.alpha; cx.translate(p.x,p.y);
      if(p._bs!=null) cx.scale(sc,sc);
      cx.rotate(p.rotation);
      draw(p); cx.restore();
    }
    if(alive){rid=requestAnimationFrame(tick);}else{P=[];rid=null;}
  }

})();
<\/script>`;
}

// ── Modal wiring ───────────────────────────
const modal = document.getElementById('out-modal');
document.getElementById('out-btn').addEventListener('click', () => {
  document.getElementById('out-code').textContent = genCode();
  modal.classList.add('open');
  document.getElementById('out-fb').textContent = '';
});
document.getElementById('m-close-btn').addEventListener('click', () => modal.classList.remove('open'));
modal.addEventListener('click', e => { if (e.target === modal) modal.classList.remove('open'); });
document.getElementById('m-copy-btn').addEventListener('click', () => {
  navigator.clipboard.writeText(document.getElementById('out-code').textContent)
    .then(() => {
      const fb = document.getElementById('out-fb');
      fb.textContent = '✅ Copied to clipboard!';
      setTimeout(() => fb.textContent = '', 2500);
    })
    .catch(() => {
      document.getElementById('out-fb').textContent = '⚠️ Copy failed — select all text manually (Ctrl+A)';
    });
});

// ── Apply URL params on load ──────────────
(function() {
  const params = new URLSearchParams(location.search);
  if (params.size === 0) return;
  suppressPreview = true;
  Object.keys(DEFAULTS).forEach(k => {
    if (params.has(k)) {
      const v = parseFloat(params.get(k));
      if (!isNaN(v)) {
        const inp = document.getElementById('s_' + k);
        if (inp) { inp.value = v; inp.dispatchEvent(new Event('input')); }
      }
    }
  });
  if (params.has('pal')) {
    params.get('pal').split(',').forEach((v, i) => {
      if (!palette[i]) return;
      if (v === '0') { palette[i].on = false; }
      else { palette[i].hex = v; palette[i].on = true; }
      const el = swDefault.children[i];
      if (!el) return;
      el.style.background = palette[i].hex;
      el.classList.toggle('on', palette[i].on);
      el.classList.toggle('off', !palette[i].on);
      const cinp = el.querySelector('input[type=color]');
      if (cinp) cinp.value = palette[i].hex;
      const xb = el.querySelector('.swatch-x');
      if (xb) xb.style.display = (palette[i].hex !== palette[i].orig) ? 'flex' : 'none';
    });
  }
  if (params.has('cust')) {
    params.get('cust').split(',').forEach((v, i) => {
      if (!customPalette[i]) return;
      const off = v.startsWith('!');
      const hex = off ? v.slice(1) : v;
      customPalette[i].hex = hex;
      customPalette[i].on = !off;
      const slot = swCustom.children[i];
      if (!slot) return;
      slot.style.background = hex;
      slot.childNodes[0].textContent = '';
      slot.classList.add('has');
      slot.classList.toggle('on', !off);
      slot.classList.toggle('off', off);
      const cinp = slot.querySelector('input[type=color]');
      if (cinp) { cinp.value = hex; cinp.style.pointerEvents = 'none'; }
    });
  }
  if (params.has('shapes')) {
    activeShapes = params.get('shapes').split(',');
    document.querySelectorAll('.sb').forEach(btn => {
      btn.classList.toggle('on', activeShapes.includes(btn.dataset.shape));
    });
  }
  if (params.has('mode')) {
    mode = params.get('mode');
    document.querySelectorAll('.mb').forEach(b => {
      b.classList.toggle('on', b.dataset.mode === mode);
    });
  }
  suppressPreview = false;
  history.replaceState(null, '', location.pathname);
})();

console.log('✅ Confetti GIF Maker loaded');
